
# Ce fichier définit les hooks Git à exécuter avant chaque commit

repos:

  - repo: local
    hooks:
      - id: pytest-smoke
        name: Exécution des tests smoke
        entry: python -m pytest tests/ -m "smoke" -v --tb=short
        language: system
        pass_filenames: false
        always_run: true

      - id: pytest-critical
        name: Exécution des tests critiques
        entry: python -m pytest tests/ -m "critical" -v --tb=short
        language: system
        pass_filenames: false
        always_run: true
