
# Ce fichier définit les hooks Git à exécuter avant chaque commit

repos:
  - repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
      - id: black
        name: Formatage avec Black
        language_version: python3
        files: ^app/.*\.py$
        args: [--check]  # Vérifie sans modifier les fichiers

  # - repo: https://github.com/PyCQA/pylint
  #   rev: v3.0.3
  #   hooks:
  #     - id: pylint
  #       name: Vérification avec Pylint
  #       entry: pylint
  #       args: ["--rcfile=.pylintrc"]
  #       language: system
  #       files: ^app/.*\.py$

  - repo: local
    hooks:
      - id: pytest-smoke
        name: Exécution des tests smoke
        entry: python -m pytest tests/ -m "smoke" -v --tb=short
        language: system
        pass_filenames: false
        always_run: true

      - id: pytest-critical
        name: Exécution des tests critiques
        entry: python -m pytest tests/ -m "critical" -v --tb=short
        language: system
        pass_filenames: false
        always_run: true
