"""empty message

Revision ID: 08b474eb6a03
Revises:
Create Date: 2026-01-07 09:43:53.900776

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "08b474eb6a03"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("etablissements", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "utilisateurs", ["id_user"], ["id_user"])

    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "utilisateurs", ["id_user"], ["id_user"])
        batch_op.create_foreign_key(None, "flans", ["id_flan"], ["id_flan"])

    with op.batch_alter_table("flans", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "utilisateurs", ["id_user"], ["id_user"])
        batch_op.create_foreign_key(None, "etablissements", ["id_etab"], ["id_etab"])

    with op.batch_alter_table("photos", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "etablissements", ["id_etab"], ["id_etab"])
        batch_op.create_foreign_key(None, "flans", ["id_flan"], ["id_flan"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("photos", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")

    with op.batch_alter_table("flans", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")

    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")

    with op.batch_alter_table("etablissements", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")

    # ### end Alembic commands ###
