"""empty message

Revision ID: 1f4ef2c17aa8
Revises:
Create Date: 2025-10-20 19:18:07.875358

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "1f4ef2c17aa8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "utilisateurs",
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column("pseudo", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id_user"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("pseudo"),
    )
    op.create_table(
        "etablissements",
        sa.Column("id_etab", sa.Integer(), nullable=False),
        sa.Column(
            "type_etab",
            sa.Enum("BOULANGERIE", "PATISSERIE", "RESTAURANT", "CAFE", name="typeetab"),
            nullable=False,
        ),
        sa.Column("nom", sa.String(length=100), nullable=False),
        sa.Column("adresse", sa.String(length=200), nullable=False),
        sa.Column("code_postal", sa.String(length=5), nullable=False),
        sa.Column("ville", sa.String(length=100), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column("telephone", sa.String(length=20), nullable=True),
        sa.Column("site_web", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("label", sa.Boolean(), nullable=True),
        sa.Column("visite", sa.Boolean(), nullable=True),
        sa.Column(
            "statut",
            sa.Enum("VALIDE", "SUPPRIME", name="statutmoderation"),
            server_default="VALID",
            nullable=False,
        ),
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["utilisateurs.id_user"],
        ),
        sa.PrimaryKeyConstraint("id_etab"),
    )
    with op.batch_alter_table("etablissements", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_etablissements_id_user"), ["id_user"], unique=False)

    op.create_table(
        "flans",
        sa.Column("id_flan", sa.Integer(), nullable=False),
        sa.Column("id_etab", sa.Integer(), nullable=False),
        sa.Column("nom", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("prix", sa.Float(), nullable=True),
        sa.Column(
            "type_saveur",
            sa.Enum("VANILLE", "NOIX", "FRUITS", "INSOLITE", "NATURE", name="typesaveur"),
            nullable=True,
        ),
        sa.Column(
            "type_pate",
            sa.Enum("FEUILLETEE", "BRISEE", "SUCREE", "SABLEE", "MIXTE", name="typepate"),
            nullable=True,
        ),
        sa.Column(
            "type_texture",
            sa.Enum(
                "GELATINEUSE", "CREMEUSE", "COSTAUD", "OEUF", "MIX_PARFAIT", name="typetexture"
            ),
            nullable=True,
        ),
        sa.Column(
            "statut",
            sa.Enum("VALIDE", "SUPPRIME", name="statutmoderation"),
            server_default="VALIDE",
            nullable=False,
        ),
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_etab"],
            ["etablissements.id_etab"],
        ),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["utilisateurs.id_user"],
        ),
        sa.PrimaryKeyConstraint("id_flan"),
    )
    with op.batch_alter_table("flans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_flans_id_user"), ["id_user"], unique=False)

    op.create_table(
        "evaluations",
        sa.Column("id_eval", sa.Integer(), nullable=False),
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column("id_flan", sa.Integer(), nullable=False),
        sa.Column("visuel", sa.Numeric(precision=2, scale=1), nullable=False),
        sa.Column("texture", sa.Numeric(precision=2, scale=1), nullable=False),
        sa.Column("pate", sa.Numeric(precision=2, scale=1), nullable=False),
        sa.Column("gout", sa.Numeric(precision=2, scale=1), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("photo", sa.String(length=255), nullable=True),
        sa.Column(
            "statut",
            sa.Enum("VALIDE", "SUPPRIME", name="statutmoderation"),
            server_default="VALIDE",
            nullable=False,
        ),
        sa.Column(
            "date_creation",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("moyenne", sa.Numeric(precision=2, scale=1), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_flan"],
            ["flans.id_flan"],
        ),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["utilisateurs.id_user"],
        ),
        sa.PrimaryKeyConstraint("id_eval"),
    )
    op.create_table(
        "photos",
        sa.Column("id_photo", sa.Integer(), nullable=False),
        sa.Column("id_flan", sa.Integer(), nullable=True),
        sa.Column("id_etab", sa.Integer(), nullable=True),
        sa.Column("type_cible", sa.Enum("FLAN", "ETABLISSEMENT", name="typecible"), nullable=False),
        sa.Column("path", sa.String(length=255), nullable=False),
        sa.Column("largeur", sa.Integer(), nullable=False),
        sa.Column("hauteur", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_etab"],
            ["etablissements.id_etab"],
        ),
        sa.ForeignKeyConstraint(
            ["id_flan"],
            ["flans.id_flan"],
        ),
        sa.PrimaryKeyConstraint("id_photo"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("photos")
    op.drop_table("evaluations")
    with op.batch_alter_table("flans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_flans_id_user"))

    op.drop_table("flans")
    with op.batch_alter_table("etablissements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_etablissements_id_user"))

    op.drop_table("etablissements")
    op.drop_table("utilisateurs")
    # ### end Alembic commands ###
