"""empty message

Revision ID: 822e8c700aa1
Revises: 08b474eb6a03
Create Date: 2026-01-13 09:07:27.246411

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "822e8c700aa1"
down_revision = "08b474eb6a03"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("etablissements", schema=None) as batch_op:
        batch_op.add_column(sa.Column("google_place_id", sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, "utilisateurs", ["id_user"], ["id_user"])

    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "utilisateurs", ["id_user"], ["id_user"])
        batch_op.create_foreign_key(None, "flans", ["id_flan"], ["id_flan"])

    with op.batch_alter_table("flans", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "utilisateurs", ["id_user"], ["id_user"])
        batch_op.create_foreign_key(None, "etablissements", ["id_etab"], ["id_etab"])

    with op.batch_alter_table("photos", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "flans", ["id_flan"], ["id_flan"])
        batch_op.create_foreign_key(None, "etablissements", ["id_etab"], ["id_etab"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("photos", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")

    with op.batch_alter_table("flans", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")

    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")

    with op.batch_alter_table("etablissements", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("google_place_id")

    # ### end Alembic commands ###
