"""empty message

Revision ID: fd3cb8773fda
Revises: 1f4ef2c17aa8
Create Date: 2026-02-13 09:53:27.315819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3cb8773fda'
down_revision = '1f4ef2c17aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, clean up duplicate establishments
    # We need to handle foreign key constraints by moving flans to the kept establishments
    
    # Create temp table with establishments to keep (one per unique nom/adresse)
    op.execute("""
        CREATE TABLE IF NOT EXISTS etablissements_to_keep AS
        SELECT MIN(id_etab) as id_etab, nom, adresse
        FROM etablissements
        GROUP BY nom, adresse
    """)
    
    # Move flans from duplicate establishments to the kept ones
    op.execute("""
        UPDATE flans f
        JOIN etablissements e ON f.id_etab = e.id_etab
        JOIN etablissements_to_keep k ON e.nom = k.nom AND e.adresse = k.adresse AND e.id_etab != k.id_etab
        SET f.id_etab = k.id_etab
    """)
    
    # Now delete the duplicate establishments
    op.execute("""
        DELETE FROM etablissements
        WHERE id_etab NOT IN (SELECT id_etab FROM etablissements_to_keep)
    """)
    
    op.execute("DROP TABLE IF EXISTS etablissements_to_keep")
    
    # Then add the unique constraint
    with op.batch_alter_table('etablissements', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_etablissement_nom_adresse', ['nom', 'adresse'])

    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_flan_evaluation', ['id_user', 'id_flan'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_flan_evaluation', type_='unique')

    with op.batch_alter_table('etablissements', schema=None) as batch_op:
        batch_op.drop_constraint('uq_etablissement_nom_adresse', type_='unique')

    # ### end Alembic commands ###
